BHoM/RAM_Toolkit

- RAM_Test/Program.cs
- RAM_Test/RAM_Test.csproj
Depends on https://github.com/BHoM/BHoM/pull/509
Fixes #79 
Due to https://github.com/BHoM/BHoM/issues/499
> RAM_Toolkit - Issue 79 - refactor queries

- RAM_Adapter/CRUD/Create.cs
- RAM_Adapter/RAM_Adapter.csproj
- RAM_Adapter/packages.config
- RAM_Engine/Convert/ToBHoM.cs
- RAM_Engine/RAM_Engine.csproj
- RAM_Engine/packages.config
- RAM_oM/RAM_oM.csproj
- RAM_oM/packages.config
> RAM_Toolkit - Issue 85 - Update RAM dll reference to Nuget

- RAM_Adapter/CRUD/Read.cs
- RAM_Engine/Convert/ToBHoM.cs
> RAM_Toolkit: add read bar trib loads

- RAM_Adapter/CRUD/Create.cs
- RAM_Adapter/CRUD/Push.cs
- RAM_Adapter/CRUD/Read.cs
- RAM_Adapter/RAM_Adapter.csproj
- RAM_Adapter/Types/DependencyTypes.cs
- RAM_Engine/Convert/ToBHoM.cs
> changed reference to Geometry.SettingOut

- RAM_Adapter/Properties/AssemblyInfo.cs
- RAM_Engine/Properties/AssemblyInfo.cs
- RAM_oM/Properties/AssemblyInfo.cs
Closes #100
Make sure that:
- All the .csproj files in the solution have the properties  `AssemblyFileVersion` to `3.0.0.0` and `AssemblyVersion` to `3.0.0.0`.
- The AssemblyCopyright reads `[assembly: AssemblyCopyright("Copyright © https://github.com/BHoM")]`
- Update `AssemblyFileVersion` to `3.0.0.0`
- Update `AssemblyVersion` to `3.0.0.0`
- Update Copyright info
> Assembly and Copyright update to 3.0

- RAM_Adapter/CRUD/Create.cs
- RAM_Adapter/RAMAdapter.cs
https://github.com/BHoM/BHoM_Adapter/pull/151
Closes #103 
Updating adapter to align with changes in the parent BHoMAdapter
All previous scripts should still be working as before.
> Aligning with changes in BHoMAdapter

- RAM_Adapter/AdapterActions/Pull.cs
- RAM_Adapter/AdapterActions/Push.cs
- RAM_Adapter/AdapterActions/_Pullmethods/ReadResults.cs
- RAM_Adapter/CRUD/Create.cs
- RAM_Adapter/CRUD/Delete.cs
- RAM_Adapter/CRUD/Read.cs
- RAM_Adapter/CRUD/UpdateObjects.cs
- RAM_Adapter/RAMAdapter.cs
- RAM_Adapter/RAM_Adapter.csproj
- RAM_Adapter/Types/Comparer.cs
- RAM_Adapter/Types/DependencyTypes.cs
- RAM_Engine/Convert/AdapterIdName.cs
- RAM_Engine/Convert/ToBHoM.cs
- RAM_Engine/RAM_Engine.csproj
https://github.com/BHoM/BHoM_Engine/pull/1371
https://github.com/BHoM/BHoM_Adapter/pull/164
https://github.com/BHoM/BHoM_UI/pull/167
- If you use Grasshopper: https://github.com/BHoM/Grasshopper_Toolkit/pull/440
- If you use Excel: https://github.com/BHoM/Excel_Toolkit/pull/172
- If you use Dynamo: https://github.com/BHoM/Dynamo_Toolkit/pull/188
- If your Toolkit needs Socket_Toolkit: https://github.com/BHoM/Socket_Toolkit/pull/57
- If your Toolkit needs Mongo_Toolkit: https://github.com/BHoM/Mongo_Toolkit/pull/82
- If you want the Adapter components to be automatically upgraded to their new version in your test scripts: https://github.com/BHoM/Versioning_Toolkit/pull/8
Closes #113 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/RAM_Toolkit/Issu …
> Aligning with changes in BHoMAdapter Refactoring Level 04

- RAM_Adapter/RAM_Adapter.csproj
- RAM_Engine/RAM_Engine.csproj
https://github.com/BHoM/BHoM/pull/704
https://github.com/BHoM/BHoM_Engine/pull/1484
https://github.com/BHoM/BHoM_Adapter/pull/193
Closes #125 
Adds references to Dimensional_oM where necessary and 'using' statments where that is necessary 
to comply with the changes in https://github.com/BHoM/BHoM/pull/704
> Update IElement references with the Dimensional_oM

- RAM_Adapter/CRUD/Create.cs
- RAM_Adapter/CRUD/Read.cs
- RAM_Adapter/Convert/AdapterIdName.cs
- RAM_Adapter/Convert/ToBHoM.cs
- RAM_Adapter/Convert/ToRAM.cs
- RAM_Adapter/RAMAdapter.cs
- RAM_Adapter/RAM_Adapter.csproj
- RAM_Engine/RAM_Engine.csproj
- RAM_oM/RAM_oM.csproj
- RAM_oM/Results/RAMFactoredEndReactions.cs
- RAM_oM/Results/RAMLineGravityLoad.cs
- RAM_oM/Results/RAMPointGravityLoad.cs
Closes #127 
Convert methods moved to adapter namespace and input attributes / object files reorganized and renamed per compliance.
> Fix compliance issues for convert methods and naming

- RAM_Adapter/RAM_Adapter.csproj
- RAM_Engine/RAM_Engine.csproj
> Common_Engine references removed

- RAM_Adapter/RAM_Adapter.csproj
- RAM_Engine/RAM_Engine.csproj
- RAM_oM/RAM_oM.csproj
Closes #141 
Copy locals false
Correct build folder for all builds
Project inside solution referenced via project, not dlls.
> Copy local false and correct project references

- RAM_Adapter/RAM_Adapter.csproj
- RAM_Engine/RAM_Engine.csproj
- RAM_oM/RAM_oM.csproj
https://github.com/BHoM/admin/issues/5
Closes #
> Update referencing and post build

- RAM_Adapter/Convert/ToBHoM.cs
https://github.com/BHoM/BHoM/pull/912
Align with changes in Structure_oM making results immutable
@JosefTaylor @enarhi  do you have a testfile for extracting RAM results?
> Align with changes in Structure_oM making results immutable

- RAM_Adapter/Convert/ToBHoM.cs
- RAM_Adapter/RAM_Adapter.csproj
https://github.com/BHoM/BHoM/pull/1030
https://github.com/BHoM/BHoM_Engine/pull/2063
Related to https://github.com/BHoM/BHoM/issues/756
- Aligning with migration of shape profiles from Geometry to Spatial
> Aligning with changes to ShapeProfiles

- RAM_Adapter/AdapterActions/Push.cs
- RAM_Adapter/CRUD/Create.cs
- RAM_Adapter/CRUD/Read.cs
- RAM_Adapter/CRUD/UpdateObjects.cs
- RAM_Adapter/Convert/ToBHoM.cs
- RAM_Adapter/Convert/ToRAM.cs
- RAM_Adapter/RAMAdapter.cs
- RAM_Adapter/RAM_Adapter.csproj
- RAM_oM/Fragments/RAMDeckData.cs
- RAM_oM/Fragments/RAMFrameData.cs
- RAM_oM/Fragments/RAMGridData.cs
- RAM_oM/Fragments/RAMId.cs
- RAM_oM/Fragments/RAMNodeForceData.cs
- RAM_oM/RAM_oM.csproj
https://github.com/BHoM/BHoM_Adapter/pull/263
https://github.com/BHoM/BHoM/pull/1033
Closes #162  
Removes CustomData and replaces it with fragments, including AdapterId fragment for RAMId.
[0 RAM Create - read - update elements - Tutorial Round Trip.zip](https://github.com/BHoM/RAM_Toolkit/files/5454924/0.RAM.Create.-.read.-.update.elements.-.Tutorial.Round.Trip.zip)
Must be merged together with https://github.com/BHoM/BHoM_Adapter/pull/263 and all others.
> Aligning to new AdapterIdFragment

- RAM_Adapter/CRUD/Create.cs
- RAM_Adapter/Convert/ToRAM.cs
https://github.com/BHoM/BHoM_Engine/pull/2146/
https://github.com/BHoM/BHoM_Engine/issues/2135
Aligning with methods being removed from Structure_Engine.
This is only changing to target another pre-existing method, so can safely be merged before others.
> Aligning with changes in Structure_Engine

- RAM_Adapter/Convert/ToBHoM.cs
- RAM_Adapter/Read/Panel.cs
Closes #195 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/RAM_Toolkit/%23196-fix-panel-pull/BuroHappold_BHoM_v5.0.beta_Create%20-%20read%20-%20update%20elements%20-%20building.gh?csf=1&web=1&e=CsS8Wd
> Improve error handling in ReadPanel()

- RAM_Adapter/AdapterActions/Pull.cs
- RAM_Adapter/AdapterActions/Push.cs
- RAM_Adapter/Convert/ToBHoM.cs
- RAM_Adapter/Create/Bar.cs
- RAM_Adapter/Create/Errors.cs
- RAM_Adapter/Create/Panel.cs
- RAM_Adapter/Create/SurfaceProperty.cs
- RAM_Adapter/Create/UniformLoadSet.cs
- RAM_Adapter/RAMAdapter.cs
- RAM_Adapter/RAM_Adapter.csproj
- RAM_Adapter/Read/Panel.cs
- RAM_Engine/Create/UniformLoadSet/RAMUniformLoadSet.cs
- RAM_Engine/RAM_Engine.csproj
https://github.com/BHoM/BHoM/pull/1339
https://github.com/BHoM/BHoM_Engine/pull/2729
https://github.com/BHoM/BHoM_Adapter/pull/318
> Align with changes in oM and Engine on Reflection -> Base

- RAM_Adapter/AdapterActions/Pull.cs
- RAM_Adapter/AdapterActions/Push.cs
- RAM_Adapter/Convert/ToBHoM.cs
- RAM_Adapter/Create/Bar.cs
- RAM_Adapter/Create/ContourLoadSet.cs
- RAM_Adapter/Create/Errors.cs
- RAM_Adapter/Create/Grid.cs
- RAM_Adapter/Create/Level.cs
- RAM_Adapter/Create/MaterialFragment.cs
- RAM_Adapter/Create/Panel.cs
- RAM_Adapter/Create/SectionProperty.cs
- RAM_Adapter/Create/SurfaceProperty.cs
- RAM_Adapter/Create/UniformLoadSet.cs
- RAM_Adapter/Create/_Create.cs
- RAM_Adapter/Read/Bar.cs
- RAM_Adapter/Read/ContourLoadSet.cs
- RAM_Adapter/Read/Errors.cs
- RAM_Adapter/Read/Grid.cs
- RAM_Adapter/Read/Level.cs
- RAM_Adapter/Read/Loads.cs
- RAM_Adapter/Read/MaterialFragment.cs
- RAM_Adapter/Read/Panel.cs
- RAM_Adapter/Read/Results.cs
- RAM_Adapter/Read/SectionProperty.cs
- RAM_Adapter/Read/SurfaceProperty.cs
- RAM_Adapter/Read/UniformLoadSet.cs
- RAM_Adapter/Read/_Read.cs
- RAM_Adapter/Types/DependencyTypes.cs
https://github.com/BHoM/BHoM/pull/1347
https://github.com/BHoM/BHoM_Engine/pull/2732
Aligning with migration of objects and methods in BHoM and Engine
> Aligning with Grid and Level migration to Spatial

- RAM_Adapter/Convert/ToBHoM.cs
- RAM_Adapter/Convert/ToRAM.cs
- RAM_Adapter/Create/Bar.cs
- RAM_Adapter/Update/Bar.cs
Done is support of, but compiles without https://github.com/BHoM/BHoM_Engine/pull/2738
Align with removed methods from Structure_Engine
> Align with changes in Structure_Engine

- RAM_Adapter/Properties/AssemblyInfo.cs
- RAM_Engine/Properties/AssemblyInfo.cs
- RAM_oM/Properties/AssemblyInfo.cs
Update Assembly Information to include description
> Update Assembly Information

- RAM_Adapter/AdapterActions/Push.cs
- RAM_Adapter/Create/Level.cs
- RAM_Adapter/Create/MaterialFragment.cs
- RAM_Adapter/Create/Panel.cs
- RAM_Adapter/Create/SectionProperty.cs
- RAM_Adapter/RAMAdapter.cs
- RAM_Adapter/Types/Comparer.cs
> Enable AdapterID for push

- RAM_Adapter/Convert/ToBHoM.cs
> Align with removal of deprecated methods

- RAM_Adapter/Properties/AssemblyInfo.cs
- RAM_Engine/Properties/AssemblyInfo.cs
- RAM_oM/Properties/AssemblyInfo.cs
Update AssemblyFileVersion to 7.3
Remove previous version attributes
> Update AssemblyFileVersion to 7.3
